---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by trifan.
--- DateTime: 03/07/2018 15:18
---
test('empty test', function()
    require "api-gateway.validation.oauth2.userProfileValidator"
end)